### ISSUE TITLE
Type extensions not processed

### ISSUE THREAD

**Issue by itallmakesense** [mirumee/ariadne-graphql-modules#6]
Hi! I was trying to makes use of `.graphql` type definitions alongside ariadne graphql modules.
Got the **ValueError: Person class was defined with __schema__ containing more than one GraphQL definition (found: ObjectTypeExtensionNode, ObjectTypeDefinitionNode)** error.

Types folder contained:
- `root.graphql`
```
type Query
```
- `person.graphql`
```
extend type Query {
  people: [Person!]!
}

type Person {
    firstName: String
    lastName: String
    age: Int
    fullName: String
}
```

Resolvers folder contained:
- `root.py`
```
from typing import Any

from ariadne import load_schema_from_path
from ariadne_graphql_modules import ObjectType, convert_case

from .person import Person


class Query(ObjectType):
    __schema__ = load_schema_from_path('types/root.graphql')
    __aliases__ = convert_case
    __requires__ = [Person]

    @staticmethod
    def resolve_people(*_: Any) -> list[dict[str, Any]]:
        return [
            {"firstName": "John", "lastName": "Doe", "age": 21},
            {"firstName": "Bob", "lastName": "Boberson", "age": 24},
        ]
```
- `person.py`
```
from typing import Any

from ariadne import load_schema_from_path
from ariadne_graphql_modules import ObjectType, convert_case


class Person(ObjectType):
    __schema__ = load_schema_from_path('types/person.graphql')
    __aliases__ = convert_case

    @staticmethod
    def resolve_person_fullname(person: Any, *_: Any) -> str:
        return "%s %s" % (person["firstName"], person["lastName"])
```

Main file contained:
```
from ariadne.asgi import GraphQL
from ariadne_graphql_modules import make_executable_schema

from resolvers import Query


# Create executable GraphQL schema
schema = make_executable_schema(Query)

# Create an ASGI app using the schema, running in debug mode
app = GraphQL(schema, debug=True)
```

And the output of the `uvicorn main:app` command is:
```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.5/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/uvicorn/main.py", line 437, in main
    run(app, **kwargs)
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/ariadne/./main.py", line 4, in <module>
    from resolvers import Query, Person
  File "/home/user/ariadne/./resolvers/__init__.py", line 1, in <module>
    from .root import Query
  File "/home/user/ariadne/./resolvers/root.py", line 6, in <module>
    from .person import Person
  File "/home/user/ariadne/./resolvers/person.py", line 7, in <module>
    class Person(ObjectType):
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ariadne_graphql_modules/object_type.py", line 36, in __init_subclass__
    parse_definition(cls.__name__, cls.__schema__)
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/ariadne_graphql_modules/utils.py", line 24, in parse_definition
    raise ValueError(
ValueError: Person class was defined with __schema__ containing more than one GraphQL definition (found: ObjectTypeExtensionNode, ObjectTypeDefinitionNode)
```

**Comment by rafalp** [comment]
This is by design. Single python type can have single type definition in `__schema__`, as per error:

> Person class was defined with __schema__ containing more than one GraphQL definition (found: ObjectTypeExtensionNode, ObjectTypeDefinitionNode)

Your schema defines two types with `extend type Query` and `type Person`.

You should have two `ObjectType` subclasses, one for `Person` and one for `Query`. Also, with Ariadne GraphQL Modules you should define as many query types as you need and let `make_executable_schema` merge them into final `Query` type. There's no need for empty root with `type Query` (which is was a valid type definition last time I've checked).

[Here's](https://github.com/rafalp/Misago/blob/starlette/misago/graphql/schema.py) an example of approach I am describing.
